#!/usr/bin/python
def combinations(L,len): #L is list [A,A+1, ... ,B]  
    if len == 1:
        return L
    return [[a,b] for a in L for b in combinations(L,len-1) if b>=a]

def main():
    L = [1,2,3,4,5]
    combinations(L,2)

if __file__ == '__main__':
    main()

