#!/usr/bin/python
import codecs
import sys
import gzip
utf8_file = sys.argv[1]

zf = gzip.open(utf8_file,'rb')
print 'Reading from', utf8_file
reader = codecs.getreader('utf-8')
contents = reader(zf)

for line in contents:
    print line

